### ISSUE TITLE
Using the wrong API?

### ISSUE THREAD

**Issue by prologic** [icholy/gist#2]
Having fixed the build error #1 it looks like we're using the wrong API?

```
$ echo 'hello world' | gist
2018/12/18 11:46:14 POST https://api.github.com/gists: 404 Not Found []
```

**Comment by icholy** [comment]
I haven't used this is a very long time. I wouldn't be surprised if the apis used are out of date.

**Comment by prologic** [comment]
Is this a dead project then?

In the meantime I've found a varient that works which I've forked
https://github.com/prologic/gister

Might be worth putting something in the README pointing folks to some
alternative working varients?

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by icholy** [comment]
I just built/tried it and it worked fine. Maybe try updating your dependencies

```
go get -d -v .
```
